#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=40gb,walltime=3:00:00
#PBS -N app-filter-wmc

surfaces=`jq -r '.surfaces' config.json`
[ ! -d wmc ] && mkdir -p wmc wmc/surfaces wmc/tracts && cp -R ${surfaces}/* ./wmc/surfaces/

time singularity exec -e docker://brainlife/dipy:1.4.1 ./filter_wmc.py
